# Generated by Django 4.1.13 on 2026-01-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='academic_qualifications',
            field=models.TextField(blank=True, help_text="e.g., Bachelor's in Mechanical Engineering, Master's in Civil Engineering"),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications and licenses'),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='country_of_practice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='engineer_type',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('consulting', 'Consulting')], default='professional', max_length=50),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to your portfolio or website', null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='professional_associations',
            field=models.TextField(blank=True, help_text='Member of professional bodies'),
        ),
    ]
